### ISSUE TITLE
ld doesn't find quadmath with latest ctng build (7)

### ISSUE THREAD

**Issue by xhochy** [conda-forge/ctng-compiler-activation-feedstock#23]
This is working:

```
conda create -n test-build6 compilers 'gxx_impl_linux-64=7.5.0=*_6' 'gfortran_impl_linux-64=7.5.0=*_6' pip
conda activate test-build6
pip wheel git+https://github.com/johnlees/glmnet_python.git@94101a0d88cc8a5505e61d97df552b6e5defab7a
```

While this fails:

```
conda create -y -n test-build7 compilers 'gxx_impl_linux-64=7.5.0=*_7' 'gfortran_impl_linux-64=7.5.0=*_7' pip
conda activate test-build7
pip wheel git+https://github.com/johnlees/glmnet_python.git@94101a0d88cc8a5505e61d97df552b6e5defab7a
```

with the following error:

```
…
  copying glmnet_python/loadGlmLib.py -> build/lib.linux-x86_64-3.8/glmnet_python
  running build_ext
  /home/uwe/miniconda3/envs/test-build7/bin/../lib/gcc/x86_64-conda-linux-gnu/7.5.0/../../../../x86_64-conda-linux-gnu/bin/ld: cannot find -lquadmath
  collect2: error: ld returned 1 exit status
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-req-build-h1hnpswb/setup.py", line 41, in <module>
      setup(name='glmnet_python',
    File "/home/uwe/miniconda3/envs/test-build7/lib/python3.8/site-packages/setuptools/__init__.py", line 161, in setup
      return distutils.core.setup(**attrs)
    File "/home/uwe/miniconda3/envs/test-build7/lib/python3.8/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/home/uwe/miniconda3/envs/test-build7/lib/python3.8/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/home/uwe/miniconda3/envs/test-build7/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/home/uwe/miniconda3/envs/test-build7/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 223, in run
      self.run_command('build')
    File "/home/uwe/miniconda3/envs/test-build7/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/uwe/miniconda3/envs/test-build7/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/home/uwe/miniconda3/envs/test-build7/lib/python3.8/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/home/uwe/miniconda3/envs/test-build7/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/uwe/miniconda3/envs/test-build7/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-req-build-h1hnpswb/setup.py", line 22, in run
      self.build_extension(ext)
    File "/tmp/pip-req-build-h1hnpswb/setup.py", line 35, in build_extension
      subprocess.check_call(['gfortran', ext.input] + gfortran_args, cwd=self.build_temp, env=env)
    File "/home/uwe/miniconda3/envs/test-build7/lib/python3.8/subprocess.py", line 364, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['gfortran', '/tmp/pip-req-build-h1hnpswb/glmnet_python/GLMnet.f', '-fPIC', '-fdefault-real-8', '-shared', '-o', '/tmp/pip-req-build-h1hnpswb/glmnet_python/GLMnet.so']' returned non-zero exit status 1.
  ----------------------------------------
  ERROR: Failed building wheel for glmnet-python
  Running setup.py clean for glmnet-python
Failed to build glmnet-python
```

**Comment by xhochy** [comment]
cc @beckermr

**Comment by isuruf** [comment]
Can you show `conda list`?
